### PR TITLE
My Enumerable

### PR DESCRIPTION
**Pull request by CarlosE-Feliz**
### Project requirements
- use pair-programming for this project. ✔
- Create a class `MyLis`t that has an instance variable` @list`. ✔
- In `MyList` implement a method `#each` that yields successive members of `@list `and uses the `MyEnumerable` module. ✔
- Create a module `MyEnumerable` that implements the following methods:
     - #all? ✔
     - #any? ✔
     - #filter ✔
- Each class and module should have a separate .rb file. ✔

### CODE REVIEW

**Review by SajjadAhmad14 — CHANGES_REQUESTED** [review]
```markdown
Hi Elim, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow GitHub flow. Please follow GitHub flow which has a `main` branch and a feature branch. PR is created from the feature to the main branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

Invalid Code Review Request **does not count** into the code reviews limit._
```

**Comment by CarlosE-Feliz** [comment]
### Note for the next reviewer

Hey there, I'm totally sure that we are following the Github flow, I really appreciate your review @SajjadAhmad14  but you are not right.

As I know the Github flow stated that we should use branches to keep an original part of the work, we won't edit that branch where we are having the original part, we should use the `main` branch as a way to save the final part of the project and the `develop`  where we are supposed to update changes until we complete the project.

We are working with 3 branches; `main`,  `dev` and `feature` I can see there the Github flow since we are working on `feature` and we are trying to merge into `dev` once we finish the project we can go ahead and merge into `main`.


I don't think that I'll be necessary but it looks like some CR don't care about checking the repo, I'll leave a picture about our branches below.

image


- Thanks in advance for the approved project, cheers!!

**Review by bimbolabuari — CHANGES_REQUESTED** [review]
Hi Team, 

You have done a good job so far 🚀  

There are some issues that you still need to work on to go to the next project but you are almost there! 🎉 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- As requested by the previous code reviewer, Kindly use [Github flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md),(any changes required in the application should be introduced in `feature` branches and approved, then merged to the main branch.) as its a general requirement for the project.

image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

--------


_Reviewed by  @bimbolabuari_

**Comment by CarlosE-Feliz** [comment]
Ok, so I'll go ahead and merge this pull request and create a new one.

**Comment by bimbolabuari** [comment]
> Ok, so I'll go ahead and merge this pull request and create a new one.

@CarlosE-Feliz, I would have suggested you follow this [github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) instructions on how to change it rather than make new pull request.

**Pull request merged**
